# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-SOAP
version:      1.04
version_from: lib/POE/Component/Server/SOAP.pm
installdirs:  site
requires:
    POE:                           0.27
    POE::Component::Server::SimpleHTTP: 1.06
    SOAP::Lite:                    0.55

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
